apiVersion: apps/v1
kind: Deployment
metadata:
  name: godbyemicroservices-postgres-oom
  namespace: godbyemicroservices-postgres-oom
  labels:
    app: godbyemicroservices-postgres-oom
  annotations:
    app.kubernetes.io/source-revision: "3119538"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: godbyemicroservices-postgres-oom
  template:
    metadata:
      labels:
        app: godbyemicroservices-postgres-oom
    spec:
      containers:
        - name: godbyemicroservices-postgres-oom
          image: godbyemicroservices-postgres-oom:3119538
          imagePullPolicy: Never
          command:
            - java
          args:
            - -Xmx18m
            - -XX:+ExitOnOutOfMemoryError
            - -XX:MaxMetaspaceSize=40m
            - -XX:ReservedCodeCacheSize=6m
            - -XX:MaxDirectMemorySize=1m
            - -Xss256k
            - -XX:+UseSerialGC
            - -XX:TieredStopAtLevel=1
            - -jar
            - app.jar
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/goodbye
            - name: SPRING_DATASOURCE_USERNAME
              value: goodbye
            - name: SPRING_DATASOURCE_PASSWORD
              value: goodbye
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 100Mi
