apiVersion: v1
kind: Service
metadata:
  name: godbyemicroservices-h2-oom
  namespace: godbyemicroservices-h2-oom
  labels:
    app: godbyemicroservices-h2-oom
spec:
  selector:
    app: godbyemicroservices-h2-oom
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
