apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devtools-kafka

resources:
  - namespace.yaml
  - zookeeper.yaml
  - kafka.yaml
  - schema-registry.yaml
  - rest-proxy.yaml
  - kafka-ui.yaml
  - redpanda-console.yaml
  - schema-registrar.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: rft-devtools-kafka
      app.kubernetes.io/managed-by: argocd
